### ISSUE TITLE
Mouse not detected

### ISSUE THREAD

**Issue by Dandumontp** [Goldfish64/SerialMouse#1]
Hi

I have tried the kext, but i have nothing with my mouse.

I have connected a Microsoft Mouse (protocol) to my MacBook Air with 2 different USB to serial adapter. Is there a way to have logs, or a special things to do ?

**Comment by Goldfish64** [comment]
What version of macOS and what adapter is being used?

**Comment by Dandumontp** [comment]
Hi

I have tested with High Sierra, Mojave and Catalina. I have just copied the kext into L/E. (not System/Library/Extension).

The mouse is working with Windows 10. For the adapter, i have tested with a PL2303 adapter and a FTDI.

Is there a special things to do ?

**Comment by Goldfish64** [comment]
https://github.com/Goldfish64/SerialMouse/commit/1a2953f4ef68e1bb1eb138688e97991eedc7c7ae should resolve.
